"""add refresh token family id

Revision ID: 78900e2e2e1c
Revises: 9ce9362716ad
Create Date: 2026-08-25 04:43:49.324254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78900e2e2e1c'
down_revision: Union[str, Sequence[str], None] = '9ce9362716ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('family_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'family_id')
    # ### end Alembic commands ###
